// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCiPytMoOOXoT1Ly4VP3jQbTFspdAGD8l8",
  authDomain: "campy-yallaa.firebaseapp.com",
  projectId: "campy-yallaa",
  storageBucket: "campy-yallaa.appspot.com",
  messagingSenderId: "335189052219",
  appId: "1:335189052219:web:69226879ab57a5bced051e",
  measurementId: "G-WY7NE1PWNN"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtE0t61TOs1eHv1vDzyYp8-EAttpPsjkY',
    appId: '1:335189052219:android:66c1f262a6c2d305ed051e',
    messagingSenderId: '335189052219',
    projectId: "campy-yallaa",
    storageBucket: "campy-yallaa.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKXP-SuRpvGNPMvefy7lrU4rBND0GJfI4',
    appId: '1:335189052219:ios:87ddebd6bff828dbed051e',
    messagingSenderId: '335189052219',
    projectId: "campy-yallaa",
    storageBucket: "campy-yallaa.appspot.com",
    iosClientId:
        '335189052219-5vvts7pus6eu8968ancdlp0f2jq0ssik.apps.googleusercontent.com',
    iosBundleId: 'com.campy-yallaa.tn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKXP-SuRpvGNPMvefy7lrU4rBND0GJfI4',
    appId: '1:335189052219:ios:87ddebd6bff828dbed051e',
    messagingSenderId: '335189052219',
    projectId: "campy-yallaa",
    storageBucket: "campy-yallaa.appspot.com",
    iosClientId:
        '335189052219-5vvts7pus6eu8968ancdlp0f2jq0ssik.apps.googleusercontent.com',
    iosBundleId: 'com.campy-yallaa.tn',
  );
}
